"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "ar" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  dir: "rtl" | "ltr"
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

// ترجمات شاملة لجميع الصفحات
const translations = {
  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.services": "خدماتنا",
    "nav.projects": "مشاريعنا",
    "nav.reports": "التقارير والتحاليل",
    "nav.contact": "تواصل معنا",
    "nav.consultation": "احصل على استشارة",
    "nav.free_consultation": "احصل على استشارة مجانية",

    // Common
    "common.learn_more": "اعرف المزيد",
    "common.view_all": "عرض الكل",
    "common.contact_us": "تواصل معنا",
    "common.get_started": "ابدأ الآن",
    "common.read_more": "اقرأ المزيد",
    "common.download": "تحميل",
    "common.view_project": "عرض المشروع",
    "common.view_details": "عرض التفاصيل",
    "common.back_to_projects": "العودة للمشاريع",
    "common.project_gallery": "معرض المشروع",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.completed": "مكتمل",
    "common.active": "نشط",
    "common.ongoing": "مستمر",
    "common.try_again": "حاول مرة أخرى",
    "common.home": "الرئيسية",
    "common.loading": "جاري التحميل...",
    "common.view_all_projects": "عرض جميع المشاريع",
    "common.home_page": "الصفحة الرئيسية",
    "common.project": "مشروع",

    // Home Page
    "home.hero.badge": "الرائدون في تكنولوجيا الخرائط",
    "home.hero.title": "شركة خرائط",
    "home.hero.kuwait": "الكويت",
    "home.hero.subtitle": "للحلول المتكاملة الحاسوبية",
    "home.hero.description":
      "نحن متخصصون في أنظمة الخرائط الإلكترونية المتقدمة باستخدام تكنولوجيا قوقل السحابية والمعلومات المكانية المفتوحة لخدمة القطاع الخاص والأهلي في دولة الكويت",
    "home.hero.discover_services": "اكتشف خدماتنا",
    "home.hero.view_work": "شاهد أعمالنا",

    // Stats
    "stats.founded": "سنة التأسيس",
    "stats.projects": "مشروع منجز",
    "stats.clients": "عميل راضي",
    "stats.support": "دعم فني",

    // About Section
    "about.badge": "من نحن؟",
    "about.title": "رؤيتنا ومهمتنا",
    "about.description": "نحن نؤمن بقوة التكنولوجيا في تشكيل مستقبل أفضل من خلال الحلول المبتكرة والرؤية الواضحة",
    "about.vision": "رؤيتنا",
    "about.mission": "مهمتنا",
    "about.vision_text": "بيانات مكانية صحيحة من أجل خرائط موضوعية وخاصة",
    "about.mission_text":
      "رفع كفاءة محتوى الخرائط في مواقع الانترنت وتطبيقات التواصل الإجتماعي لتحقيق تطلعات رواد الأعمال والمستخدمين",
    "about.company_history": "تاريخ الشركة",
    "about.founded_in": "تأسست في عام 2022",
    "about.history_text":
      "تأسست خرائط الكويت للحلول المتكاملة الحاسوبية في عام 2022، وتسعى الشركة إلى التوسع في مشاريع نظم المعلومات المكانية وسوق مرئيات الأقمار الصناعية.",
    "about.company_name": "شركة خرائط الكويت",
    "about.company_overview": "نبذة عن الشركة",
    "about.company_description": "شركة أعمال متخصصة في أنظمة الخرائط الإلكترونية باستخدام أنظمة قوقل السحابية وتكنولوجيا المعلومات المكانية المفتوحة. نقدم حلولاً فريدة وتطبيقات مرنة لجمع ومعالجة وتوقيع البيانات المكانية على أنظمة ذكية.",
    "about.company_services": "تخدم أنشطة القطاع الخاص والأهلي في دولة الكويت من خلال تقديم حلول تقنية متطورة تواكب أحدث التطورات العالمية في مجال تكنولوجيا المعلومات المكانية.",
    "about.discover_services": "اكتشف خدماتنا",
    "about.vision_mission_title": "رؤيتنا ومهمتنا",
    "about.values_title": "قيمنا الأساسية",
    "about.values_subtitle": "ما نؤمن به",
    "about.quality_excellence": "الجودة والتميز",
    "about.quality_description": "نلتزم بتقديم أعلى معايير الجودة في جميع خدماتنا وحلولنا التقنية مع ضمان التميز في كل مشروع",
    "about.collaboration_partnership" : "التعاون والشراكة",
    "about.collaboration_description": "نؤمن بقوة العمل الجماعي وبناء شراكات استراتيجية طويلة المدى مع عملائنا لتحقيق النجاح المشترك",
    "about.innovation_development" : "الابتكار والتطوير",
    "about.innovation_description" : "نسعى دائماً لتطوير حلول مبتكرة تواكب أحدث التقنيات العالمية وتلبي احتياجات السوق المتطورة",
    "about.reliability_security" : "الموثوقية والأمان",
    "about.reliability_description" : "نضمن أعلى مستويات الأمان وحماية البيانات مع الالتزام بالمعايير الدولية للجودة والموثوقية",
    "about.team_structure": "هيكل الشركة",
    "about.team_subtitle": "فريق متخصص من الخبراء في مجال تكنولوجيا المعلومات المكانية",
    "about.executive_management": "الإدارة التنفيذية",
    "about.executive_description": "قيادة استراتيجية وإدارة المشاريع بخبرة عالية",
    "about.technical_team": "الفريق التقني",
    "about.technical_description": "مطورون ومهندسون متخصصون في أحدث التقنيات",
    "about.research_development": "قسم البحث والتطوير",
    "about.research_description": "ابتكار وتطوير الحلول الجديدة والمتطورة",
    "about.customer_service": "خدمة العملاء",
    "about.customer_description": "دعم ومتابعة العملاء على مدار الساعة",
    "about.success_journey": "رحلة النجاح",
    "about.founded_2022": "تأسست في عام 2022",
    "about.excellence_innovation": "بداية رحلة التميز والابتكار",
    "about.company_expansion": "تأسست خرائط الكويت للحلول المتكاملة الحاسوبية في عام 2022، وتسعى الشركة إلى التوسع في مشاريع نظم المعلومات المكانية وسوق مرئيات الأقمار الصناعية ومشاريع جمع ومعالجة البيانات الجغرافية وحلول قواعد البيانات الضخمة.",
    "about.economic_contribution": "نهدف إلى توفير هذه المخرجات إلى قطاع الشركات الخاصة في مجال التجارة الإلكترونية والتقليدية وملاك العقار ورواد الأعمال، مما يساهم في تطوير الاقتصاد الرقمي في دولة الكويت.",
    "about.join_success": "انضم إلى رحلة النجاح",
    "about.join_description": "كن جزءاً من قصة نجاحنا واكتشف كيف يمكننا مساعدتك في تحقيق أهدافك",
    "services.main_services": "خدماتنا الرئيسية",
    "services.comprehensive_solutions": "حلول شاملة ومتطورة",
    "services.spatial_data_collection": "حلول جمع البيانات المكانية وتحليل مرئيات الأقمار الصناعية",
    "services.spatial_data_description": "تقدم خرائط الكويت خدمة جمع البيانات المكانية باختلاف مصادرها عن طريق تقنيات الاستشعار عن بعد وبرامج تكنولوجيا المعلومات المكانية المفتوحة المصدر",
    "services.field_data_collection": "جمع البيانات من الميدان",
    "services.custom_survey_models": "بناء نماذج المسح المخصصة",
"services.project_sharing": "مشاركة ونشر المشروع مع طاقم العمل الميداني",
    "services.satellite_analysis": "تحليل مرئيات الأقمار الصناعية والصور الملتقطة بالدرون",
    "services.features": "المميزات:",
    "services.benefits": "الفوائد:",
    "services.high_accuracy": "دقة عالية في البيانات",
    "services.time_effort_saving": "توفير الوقت والجهد",
    "services.comprehensive_reports": "تقارير شاملة ومفصلة",
    "services.electronic_mobile_maps": "خرائط إلكترونية والهاتف المحمول",
    "services.electronic_maps_description": "خرائط إلكترونية تفاعلية على مواقع الويب وتطبيقات على الهاتف المحمول لإضافة وتعديل البيانات المكانية",
    "services.features": "المميزات:",
    "services.interactive_web_maps": "خرائط تفاعلية للويب",
    "services.mobile_applications": "تطبيقات الهاتف المحمول",
    "services.spatial_data_editing": "إضافة وتعديل البيانات المكانية",
    "services.geographic_phenomena": "عرض الظواهر الجغرافية",
    "services.benefits": "الفوائد:",
    "services.user_friendly": "واجهة سهلة الاستخدام",
    "services.device_compatibility": "متوافق مع جميع الأجهزة",
    "services.instant_updates": "تحديثات فورية",
    "services.business_location_publishing": "نشر وتحسين موقع النشاط التجاري",
    "services.business_location_description": "إضافة وتعديل وتحسين بيانات موقع النشاط التجاري ونشرها على وسائل تطبيقات التواصل الاجتماعي المختلفة",
    "services.features": "المميزات:",
    "services.features services.search_optimization": "تحسين الظهور في محركات البحث",
    "services.social_media_publishing": "النشر على وسائل التواصل الاجتماعي",
    "services.location_data_updates": "تحديث بيانات الموقع",
    "services.digital_marketing": "استراتيجيات التسويق الرقمي",
    "services.benefits": "الفوائد:",
    "services.customer_reach": "زيادة الوصول للعملاء",
    "services.digital_visibility": "تحسين الرؤية الرقمية",
    "services.sales_growth": "نمو المبيعات",
    "services.specialized_service": "خدمة متخصصة",
    "services.google_business_account": "خدمة الحساب التجاري في خرائط قوقل",
    "services.google_business_description": "خدمات شاملة لإدارة وتحسين حسابك التجاري في خرائط قوقل لزيادة الوصول والمبيعات",
    "services.account_verification": "توثيق الحساب التجاري في خرائط قوقل",
    "services.account_verification_desc": "توثيق ملكية الحساب التجاري وصيانة الحساب",
    "services.data_management": "إدارة ومعالجة البيانات",
    "services.data_management_desc": "إدارة بيانات الحسابات ومعالجة الصور الفوتوغرافية وتعديل البيانات والأخطاء",
    "services.business_documentation": "توثيق ونشر الأنشطة التجارية",
    "services.business_documentation_desc": "المواقع الإلكترونية ودليل الشركات ومحرك بحث خرائط قوقل",
    "services.performance_reports": "تقارير الأداء وتقارير تنافسية",
    "services.performance_reports_desc": "التنافسية على الكلمات الدالة وإدارة المراجعات وتقارير الأداء",
    "services.advertising_campaigns": "الحملات الإعلانية",
    "services.advertising_campaigns_desc": "إعلانات خرائط قوقل ومحرك بحث قوقل بأنواعها المختلفة",
    "services.distinguished_service": "خدمة مميزة",
    "services.dot_service": "خدمة النقطة (The Dot)",
    "services.dot_advanced_solutions": "حلول الخرائط المتقدمة",
    "services.dot_description": "تهدف شركة خرائط الكويت إلى مساعدة أصحاب الأعمال في مختلف الصناعات في إضافة كياناتهم والمعلومات ذات الصلة إلى منصات الخرائط عبر الإنترنت، مع التركيز بشكل أساسي على خرائط قوقل.",
    "services.dot_comprehensive": "من خلال توفير حلول شاملة لرسم الخرائط ثنائية الأبعاد تشمل المباني ومواقف السيارات والمحلات التجارية والمناظر الطبيعية، تعمل الشركة على تسهيل الرؤية المحسنة وإمكانية الوصول للشركات.",
    "services.dot_features": "مميزات خدمة مشروع DOT",
    "services.start_project": "ابدأ مشروعك اليوم",
    "services.free_consultation": "هل تحتاج إلى استشارة مجانية؟",
    "services.consultation_description": "تواصل معنا اليوم واكتشف كيف يمكن لخدماتنا المتخصصة أن تساعد في تطوير عملك وتحقيق أهدافك",
    "services.get_consultation": "احصل على استشارة مجانية",
    "services.view_work": "شاهد أعمالنا",
    "services.search_optimization": "تحسين الظهور في محركات البحث",
    "reports.badge": "تحليلات وتقارير متقدمة",
    "reports.title": "التقارير والتحاليل",
    "reports.description": "تقارير شاملة وتحليلات متقدمة تساعدك في اتخاذ قرارات مدروسة وتحسين أداء عملك",
    "reports.completed_reports": "تقرير منجز",
    "reports.satisfied_clients": "عميل راضي",
    "reports.data_accuracy": "دقة البيانات",
    "reports.continuous_updates": "تحديث مستمر",
    "reports.report_types_badge": "أنواع التقارير",
    "reports.report_types_title": "تقارير شاملة ومتخصصة",
    "reports.business_performance": "تقارير الأداء التجاري",
    "reports.business_performance_desc": "تحليل شامل لأداء الحساب التجاري في خرائط قوقل مع مؤشرات الأداء الرئيسية",
    "reports.report_includes": "يشمل التقرير:",
    "reports.business_performance_feature1": "تحليل الزيارات والمشاهدات",
    "reports.business_performance_feature2": "معدل التفاعل مع المحتوى",
    "reports.business_performance_feature3": "تحليل المراجعات والتقييمات",
    "reports.business_performance_feature4": "مقارنة الأداء مع المنافسين",
    "reports.deliverables": "المخرجات:",
    "reports.business_performance_deliverable1": "تقرير شهري مفصل",
    "reports.business_performance_deliverable2": "رسوم بيانية تفاعلية",
    "reports.business_performance_deliverable3": "توصيات للتحسين",
    "reports.competitive_analysis": "تقارير التحليل التنافسي",
    "reports.competitive_analysis_desc": "دراسة مقارنة شاملة لموقعك التنافسي في السوق مع تحليل نقاط القوة والضعف",
    "reports.competitive_analysis_feature1": "تحليل المنافسين المباشرين",
    "reports.competitive_analysis_feature2": "مقارنة الكلمات المفتاحية",
    "reports.competitive_analysis_feature3": "تحليل استراتيجيات التسويق",
    "reports.competitive_analysis_feature4": "فرص النمو والتطوير",
    "reports.competitive_analysis_deliverable1": "تقرير تنافسي ربع سنوي",
    "reports.competitive_analysis_deliverable2": "خطة عمل استراتيجية",
    "reports.competitive_analysis_deliverable3": "مصفوفة المنافسين",
    "reports.performance_monitoring": "تقارير مراقبة الأداء",
    "reports.performance_monitoring_desc": "مراقبة مستمرة لأداء المشاريع والأنظمة مع تنبيهات فورية وتحليل الاتجاهات",
    "reports.performance_monitoring_feature1": "مراقبة الأداء في الوقت الفعلي",
    "reports.performance_monitoring_feature2": "تنبيهات الأخطاء والمشاكل",
    "reports.performance_monitoring_feature3": "تحليل اتجاهات الاستخدام",
    "reports.performance_monitoring_feature4": "تقارير الصيانة الوقائية",
    "reports.performance_monitoring_deliverable1": "لوحة تحكم تفاعلية",
    "reports.performance_monitoring_deliverable2": "تقارير أسبوعية",
    "reports.performance_monitoring_deliverable3": "تنبيهات فورية",
    "reports.spatial_data": "تقارير البيانات المكانية",
    "reports.spatial_data_desc": "تحليل معمق للبيانات الجغرافية والمكانية مع إحصائيات دقيقة ورؤى قيمة",
    "reports.spatial_data_feature1":"تحليل التوزيع الجغرافي",
    "reports.spatial_data_feature2": "خرائط الكثافة السكانية",
    "reports.spatial_data_feature3": "تحليل أنماط الحركة",
    "reports.spatial_data_feature4": "إحصائيات المناطق الجغرافية",
    "reports.spatial_data_deliverable1": "خرائط تحليلية",
    "reports.spatial_data_deliverable2": "قواعد بيانات مكانية",
    "reports.spatial_data_deliverable3": "تقارير إحصائية",
    "reports.sample_reports_badge": "نماذج من أعمالنا",
    "reports.sample_reports_title": "تقارير منجزة",
    "reports.sample_reports_desc": "أمثلة على التقارير والتحليلات التي أنجزناها لعملائنا",
    "reports.sample_report1_title": "تقرير أداء مول 360",
    "reports.sample_report1_type": "تقرير أداء",
    "reports.sample_report1_pages": "25 صفحة",
    "reports.sample_report1_desc": "تحليل شامل لأداء الحساب التجاري لمول 360 في خرائط قوقل",
    "reports.sample_report1_date": "ديسمبر 2024",
    "reports.key_results": "النتائج الرئيسية:",
    "reports.sample_report1_highlight1": "زيادة الزيارات بنسبة 45%",
    "reports.sample_report1_highlight2": "تحسن التقييمات إلى 4.8/5",
    "reports.sample_report1_highlight3": "نمو المراجعات بنسبة 60%",
    "reports.sample_report2_title": "دراسة تنافسية للمولات التجارية",
    "reports.sample_report2_type": "تحليل تنافسي",
    "reports.sample_report2_pages": "40 صفحة",
    "reports.sample_report2_desc": "تحليل مقارن للمولات التجارية الرئيسية في الكويت",
    "reports.sample_report2_date": "نوفمبر 2024",
    "reports.sample_report2_highlight1": "تحليل 15 مول رئيسي",
    "reports.sample_report2_highlight2": "مقارنة الاستراتيجيات",
    "reports.sample_report2_highlight3": "فرص النمو المحددة",
    "reports.sample_report3_title": "تقرير البيانات المكانية للكويت",
    "reports.sample_report3_type": "بيانات مكانية",
    "reports.sample_report3_pages": "60 صفحة",
    "reports.sample_report3_desc": "تحليل شامل للبيانات المكانية والجغرافية لدولة الكويت",
    "reports.sample_report3_date": "أكتوبر 2024",
    "reports.sample_report3_highlight1": "خرائط تفاعلية",
    "reports.sample_report3_highlight2": "إحصائيات ديموغرافية",
    "reports.sample_report3_highlight3": "تحليل التوزيع السكاني",
    "reports.view_report": "عرض التقرير",
    "reports.report_features_badge": "مميزات تقاريرنا",
    "reports.report_features_title": "لماذا تختار تقاريرنا؟",
    "reports.feature4_title": "توقعات مستقبلية",
    "reports.feature4_desc": "تنبؤات وتوقعات مبنية على تحليل البيانات التاريخية",
    "reports.feature3_title": "تحليل شامل ومتكامل",
    "reports.feature3_desc": "نظرة شاملة تغطي جميع جوانب الأداء والتطوير",
    "reports.feature2_title": "بيانات دقيقة وموثوقة",
    "reports.feature2_desc": "معلومات محدثة ودقيقة من مصادر موثوقة ومتعددة",
    "reports.feature1_title": "رؤى قابلة للتنفيذ",
    "reports.feature1_desc": "تحليلات عملية يمكن تطبيقها مباشرة لتحسين الأداء",
    "reports.cta_badge": "احصل على تقريرك المخصص",
    "reports.cta_title": "هل تحتاج إلى تقرير مخصص؟",
    "reports.cta_desc": "تواصل معنا اليوم واحصل على تقرير مفصل وتحليل شامل لعملك أو مشروعك",
    "reports.cta_button2": "اكتشف خدماتنا",
    "reports.cta_button1": "اطلب تقريرك الان",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // Services
    "services.badge": "خدماتنا المتميزة",
    "services.title": "حلول متكاملة ومبتكرة",
    "services.description": "نقدم مجموعة شاملة من الخدمات المتطورة في مجال الخرائط الإلكترونية والبيانات المكانية",
    "services.spatial_data": "حلول البيانات المكانية",
    "services.spatial_data_desc": "جمع وتحليل البيانات المكانية باستخدام تقنيات الاستشعار عن بعد والذكاء الاصطناعي",
    "services.digital_maps": "خرائط إلكترونية ومحمولة",
    "services.digital_maps_desc": "تطوير خرائط تفاعلية متقدمة للويب وتطبيقات الهاتف المحمول",
    "services.google_business": "الحساب التجاري في قوقل",
    "services.google_business_desc": "إدارة وتحسين الحسابات التجارية في خرائط قوقل لزيادة الظهور",
    "services.the_dot": "خدمة النقطة (The Dot)",
    "services.the_dot_desc": "حلول شاملة لرسم الخرائط ثنائية الأبعاد للمباني والمحلات التجارية",
    "services.view_all": "عرض جميع الخدمات",

    // Projects
    "projects.badge": "مشاريعنا المميزة",
    "projects.title": "مشاريعنا",
    "projects.view_all": "عرض جميع المشاريع",
    "projects.description": "استكشف مجموعة من المشاريع المبتكرة والحلول التقنية المتقدمة التي نفخر بإنجازها",
    "projects.hero_description": "استكشف مجموعة من المشاريع المبتكرة والحلول التقنية المتقدمة التي نفخر بإنجازها",
    "projects.main_projects": "5",
    "projects.showcase_images": "صورة توضيحية",
    "projects.different_sectors": "قطاع مختلف",
    "projects.success_rate": "معدل النجاح",
    "projects.our_main_projects": "مشاريعنا الرئيسية",
    "projects.technologies_used": "التقنيات المستخدمة:",
    "projects.project_title": "مشروع",
    "projects.project_description": "وصف المشروع",
    "projects.project_details": "تفاصيل المشروع",
    "projects.under_development": "قيد التطوير",
    "projects.total_projects": "إجمالي المشاريع",
    "projects.completed_projects": "مشاريع مكتملة",
    "projects.active_projects": "مشاريع نشطة",
    "projects.categories": "فئات",

    // CTA
    "cta.badge": "ابدأ رحلتك معنا",
    "cta.title": "هل أنت مستعد لبدء مشروعك؟",
    "cta.description": "تواصل معنا اليوم واكتشف كيف يمكن لحلولنا المتقدمة أن تساعد في نمو عملك وتحقيق أهدافك التقنية",
    "cta.contact_now": "تواصل معنا الآن",
    "cta.explore_services": "استكشف خدماتنا",

    // Contact
    "contact.badge": "نحن هنا لمساعدتك",
    "contact.title": "تواصل معنا",
    "contact.description": "نحن هنا لمساعدتك في تحقيق أهدافك التقنية وتقديم أفضل الحلول المبتكرة",
    "contact.send_message": "أرسل رسالة",
    "contact.reply_24h": "سنرد عليك خلال 24 ساعة",
    "contact.first_name": "الاسم الأول",
    "contact.first_name_placeholder": "أدخل اسمك الأول",
    "contact.last_name": "الاسم الأخير",
    "contact.last_name_placeholder": "أدخل اسمك الأخير",
    "contact.email": "البريد الإلكتروني",
    "contact.email_placeholder": "أدخل بريدك الإلكتروني",
    "contact.phone": "رقم الهاتف",
    "contact.phone_placeholder": "أدخل رقم هاتفك",
    "contact.company": "الشركة",
    "contact.company_placeholder": "أدخل اسم شركتك (اختياري)",
    "contact.subject": "الموضوع",
    "contact.subject_placeholder": "أدخل موضوع رسالتك",
    "contact.message": "الرسالة",
    "contact.message_placeholder": "أدخل تفاصيل رسالتك هنا...",
    "contact.send": "إرسال الرسالة",
    "contact.contact_info": "معلومات التواصل",
    "contact.connect_us": "تواصل معنا",
    "contact.connect_methods": "يمكنك التواصل معنا من خلال الطرق التالية",
    "contact.address": "العنوان",
    "contact.kuwait": "دولة الكويت",
    "contact.phone_number": "+965 555 912 92",
    "contact.email_address": "info@q8maps.com",
    "contact.website": "الموقع الإلكتروني",
    "contact.website_url": "https://q8maps.com/",
    "contact.working_hours": "ساعات العمل",
    "contact.hours": "الأحد - الخميس: 8:00 ص - 5:00 م",
    "contact.location": "موقعنا",
    "contact.map_location": "موقعنا على الخريطة",
    "contact.response_hours": "ساعة للرد",
    "contact.response_rate": "معدل الاستجابة",
    "contact.satisfaction_rate": "معدل الرضا",
    "contact.faq": "الأسئلة الشائعة",
    "contact.frequently_asked": "الأسئلة الأكثر شيوعاً",
    "contact.feel_free": "لا تتردد في التواصل",
    "contact.ready_help": "نحن مستعدون لمساعدتك",
    "contact.expert_team": "فريقنا من الخبراء جاهز لتقديم أفضل الحلول التقنية لمشروعك",

    // Footer
    "footer.company_desc": "شركة متخصصة في أنظمة الخرائط الإلكترونية وتكنولوجيا المعلومات المكانية المفتوحة",
    "footer.quick_links": "روابط سريعة",
    "footer.our_services": "خدماتنا",
    "footer.contact_info": "تواصل معنا",
    "footer.follow_us": "تابعنا",
    "footer.rights": "جميع الحقوق محفوظة",

    // Project Details
    "project.project": "مشروع",
    "project.project_information": "معلومات المشروع",
    "project.year": "السنة",
    "project.duration": "المدة",
    "project.client": "العميل",
    "project.technologies_used": "التقنيات المستخدمة",
    "project.key_features": "المميزات الرئيسية",
    "project.project_objectives": "أهداف المشروع",
    "project.need_similar_project": "هل تحتاج مشروع مشابه؟",
    "project.contact_us_discuss": "تواصل معنا لمناقشة مشروعك والحصول على استشارة مجانية",
    "project.other_projects": "مشاريع أخرى",
    "project.project_not_found": "المشروع غير موجود",
    "project.project_not_found_message": "عذراً، لم نتمكن من العثور على المشروع المطلوب. ربما تم حذفه أو تغيير رابطه.",

    // Error Messages
    "error.something_went_wrong": "حدث خطأ غير متوقع",
    "error.loading_project_details":
      "نعتذر، حدث خطأ أثناء تحميل تفاصيل المشروع. يرجى المحاولة مرة أخرى أو العودة إلى صفحة المشاريع.",
    "error.error_details": "تفاصيل الخطأ (للمطورين)",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.services": "Services",
    "nav.projects": "Projects",
    "nav.reports": "Reports & Analytics",
    "nav.contact": "Contact Us",
    "nav.consultation": "Get Consultation",
    "nav.free_consultation": "Get Free Consultation",

    // Common
    "common.learn_more": "Learn More",
    "common.view_all": "View All",
    "common.contact_us": "Contact Us",
    "common.get_started": "Get Started",
    "common.read_more": "Read More",
    "common.download": "Download",
    "common.view_project": "View Project",
    "common.view_details": "View Details",
    "common.back_to_projects": "Back to Projects",
    "common.project_gallery": "Project Gallery",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.completed": "Completed",
    "common.active": "Active",
    "common.ongoing": "Ongoing",
    "common.try_again": "Try Again",
    "common.home": "Home",
    "common.loading": "Loading...",
    "common.view_all_projects": "View All Projects",
    "common.home_page": "Home Page",
    "common.project": "Project",

    // Home Page
    "home.hero.badge": "Leaders in Mapping Technology",
    "home.hero.title": "Kuwait Maps Company",
    "home.hero.kuwait": " ",
    "home.hero.subtitle": "For Integrated Computing Solutions",
    "home.hero.description":
      "We specialize in advanced electronic mapping systems using Google cloud technology and open spatial information to serve the private and civil sectors in the State of Kuwait",
    "home.hero.discover_services": "Discover Our Services",
    "home.hero.view_work": "View Our Work",

    // Stats
    "stats.founded": "Year Founded",
    "stats.projects": "Completed Projects",
    "stats.clients": "Satisfied Clients",
    "stats.support": "Technical Support",

    // About Section
    "about.badge": "Who We Are?",
    "about.title": "Our Vision & Mission",
    "about.description":
      "We believe in the power of technology to shape a better future through innovative solutions and clear vision",
    "about.vision": "Our Vision",
    "about.mission": "Our Mission",
    "about.vision_text": "Accurate spatial data for objective and specialized maps",
    "about.mission_text":
      "Improving the efficiency of map content on websites and social media applications to achieve the aspirations of entrepreneurs and users",
    "about.company_history": "Company History",
    "about.founded_in": "Founded in 2022",
    "about.history_text":
      "Kuwait Maps for Integrated Computing Solutions was established in 2022, and the company seeks to expand in spatial information systems projects and the satellite imagery market.",

    // Services
    "services.badge": "Our Distinguished Services",
    "services.title": "Integrated and Innovative Solutions",
    "services.description":
      "We provide a comprehensive range of advanced services in electronic mapping and spatial data",
    "services.spatial_data": "Spatial Data Solutions",
    "services.spatial_data_desc":
      "Collecting and analyzing spatial data using remote sensing techniques and artificial intelligence",
    "services.digital_maps": "Digital and Mobile Maps",
    "services.digital_maps_desc": "Developing advanced interactive maps for web and mobile applications",
    "services.google_business": "Google Business Account",
    "services.google_business_desc": "Managing and optimizing business accounts on Google Maps to increase visibility",
    "services.the_dot": "The Dot Service",
    "services.the_dot_desc": "Comprehensive solutions for 2D mapping of buildings and commercial stores",
    "services.view_all": "View All Services",

    // Projects
    "projects.badge": "Our Featured Projects",
    "projects.title": "Our Projects",
    "projects.view_all": "View All Projects",
    "projects.description":
      "Explore a collection of innovative projects and advanced technical solutions we're proud to have accomplished",
    "projects.hero_description":
      "Explore a collection of innovative projects and advanced technical solutions we're proud to have accomplished",
    "projects.main_projects": "5",
    "projects.showcase_images": "Showcase Images",
    "projects.different_sectors": "Different Sectors",
    "projects.success_rate": "Success Rate",
    "projects.our_main_projects": "Our Main Projects",
    "projects.technologies_used": "Technologies Used:",
    "projects.project_title": "Project",
    "projects.project_description": "Project Description",
    "projects.project_details": "Project Details",
    "projects.under_development": "Under Development",
    "projects.total_projects": "Total Projects",
    "projects.completed_projects": "Completed Projects",
    "projects.active_projects": "Active Projects",
    "projects.categories": "Categories",

    // CTA
    "cta.badge": "Start Your Journey With Us",
    "cta.title": "Are You Ready to Start Your Project?",
    "cta.description":
      "Contact us today and discover how our advanced solutions can help grow your business and achieve your technical goals",
    "cta.contact_now": "Contact Us Now",
    "cta.explore_services": "Explore Our Services",

    // Contact
    "contact.badge": "We're Here to Help You",
    "contact.title": "Contact Us",
    "contact.description":
      "We're here to help you achieve your technical goals and provide the best innovative solutions",
    "contact.send_message": "Send Message",
    "contact.reply_24h": "We'll reply within 24 hours",
    "contact.first_name": "First Name",
    "contact.first_name_placeholder": "Enter your first name",
    "contact.last_name": "Last Name",
    "contact.last_name_placeholder": "Enter your last name",
    "contact.email": "Email",
    "contact.email_placeholder": "Enter your email address",
    "contact.phone": "Phone",
    "contact.phone_placeholder": "Enter your phone number",
    "contact.company": "Company",
    "contact.company_placeholder": "Enter your company name (optional)",
    "contact.subject": "Subject",
    "contact.subject_placeholder": "Enter your message subject",
    "contact.message": "Message",
    "contact.message_placeholder": "Enter your message details here...",
    "contact.send": "Send Message",
    "contact.contact_info": "Contact Information",
    "contact.connect_us": "Connect With Us",
    "contact.connect_methods": "You can reach us through the following methods",
    "contact.address": "Address",
    "contact.kuwait": "State of Kuwait",
    "contact.phone_number": "+965 555 912 92",
    "contact.email_address": "info@q8maps.com",
    "contact.website": "Website",
    "contact.website_url": "https://q8maps.com/",
    "contact.working_hours": "Working Hours",
    "contact.hours": "Sunday - Thursday: 8:00 AM - 5:00 PM",
    "contact.location": "Our Location",
    "contact.map_location": "Our Location on Map",
    "contact.response_hours": "Response Hours",
    "contact.response_rate": "Response Rate",
    "contact.satisfaction_rate": "Satisfaction Rate",
    "contact.faq": "FAQ",
    "contact.frequently_asked": "Frequently Asked Questions",
    "contact.feel_free": "Feel Free to Contact",
    "contact.ready_help": "We're Ready to Help",
    "contact.expert_team": "Our expert team is ready to provide the best technical solutions for your project",

    // Footer
    "footer.company_desc":
      "A company specialized in electronic mapping systems and open spatial information technology",
    "footer.quick_links": "Quick Links",
    "footer.our_services": "Our Services",
    "footer.contact_info": "Contact Us",
    "footer.follow_us": "Follow Us",
    "footer.rights": "All Rights Reserved",

    // Project Details
    "project.project": "Project",
    "project.project_information": "Project Information",
    "project.year": "Year",
    "project.duration": "Duration",
    "project.client": "Client",
    "project.technologies_used": "Technologies Used",
    "project.key_features": "Key Features",
    "project.project_objectives": "Project Objectives",
    "project.need_similar_project": "Need a Similar Project?",
    "project.contact_us_discuss": "Contact us to discuss your project and get a free consultation",
    "project.other_projects": "Other Projects",
    "project.project_not_found": "Project Not Found",
    "project.project_not_found_message":
      "Sorry, we couldn't find the requested project. It may have been deleted or its link changed.",

    // Error Messages
    "error.something_went_wrong": "Something went wrong",
    "error.loading_project_details":
      "Sorry, an error occurred while loading the project details. Please try again or return to the projects page.",
    "error.error_details": "Error Details (for developers)",


  "about.badge": "Who are we?",
  "about.title": "Our Vision and Mission",
  "about.description": "We believe in the power of technology to shape a better future through innovative solutions and clear vision.",
  "about.vision": "Our Vision",
  "about.mission": "Our Mission",
  "about.vision_text": "Accurate spatial data for objective and customized maps.",
  "about.mission_text": "Enhancing the quality of map content on websites and social media platforms to meet the aspirations of entrepreneurs and users.",
  "about.company_history": "Company History",
  "about.founded_in": "Founded in 2022",
  "about.history_text": "Kuwait Maps for Integrated Computer Solutions was founded in 2022 and aims to expand in GIS projects and the satellite imagery market.",
  "about.company_name": "Kuwait Maps Company",
  "about.company_overview": "Company Overview",
  "about.company_description": "A business company specialized in electronic mapping systems using Google cloud systems and open-source spatial information technologies. We offer unique solutions and flexible applications for collecting, processing, and tagging spatial data on intelligent systems.",
  "about.company_services": "Serving the private and non-profit sectors in Kuwait by providing advanced technological solutions aligned with the latest global developments in geospatial technology.",
  "about.discover_services": "Discover Our Services",
  "about.vision_mission_title": "Our Vision and Mission",
  "about.values_title": "Our Core Values",
  "about.values_subtitle": "What We Believe In",
  "about.quality_excellence": "Quality and Excellence",
  "about.quality_description": "We are committed to delivering the highest standards of quality in all our services and tech solutions while ensuring excellence in every project.",
  "about.collaboration_partnership": "Collaboration and Partnership",
  "about.collaboration_description": "We believe in the power of teamwork and building long-term strategic partnerships with our clients to achieve mutual success.",
  "about.innovation_development": "Innovation and Development",
  "about.innovation_description": "We continuously strive to develop innovative solutions that keep pace with the latest global technologies and meet evolving market needs.",
  "about.reliability_security": "Reliability and Security",
  "about.reliability_description": "We ensure the highest levels of data security and protection while adhering to international standards of quality and reliability.",
  "about.team_structure": "Company Structure",
  "about.team_subtitle": "A specialized team of experts in geospatial technology",
  "about.executive_management": "Executive Management",
  "about.executive_description": "Strategic leadership and expert project management",
  "about.technical_team": "Technical Team",
  "about.technical_description": "Developers and engineers specialized in cutting-edge technologies",
  "about.research_development": "Research and Development Department",
  "about.research_description": "Innovating and developing new and advanced solutions",
  "about.customer_service": "Customer Service",
  "about.customer_description": "24/7 client support and follow-up",
  "about.success_journey": "The Success Journey",
  "about.founded_2022": "Founded in 2022",
  "about.excellence_innovation": "The beginning of a journey of excellence and innovation",
  "about.company_expansion": "Kuwait Maps for Integrated Computer Solutions was founded in 2022 and aims to expand in GIS projects, the satellite imagery market, geographic data collection and processing projects, and big data solutions.",
  "about.economic_contribution": "We aim to provide these outputs to private sector companies in e-commerce, traditional trade, real estate owners, and entrepreneurs, contributing to the development of the digital economy in Kuwait.",
  "about.join_success": "Join the Journey of Success",
  "about.join_description": "Be part of our success story and discover how we can help you achieve your goals",
  
  "services.main_services": "Our Main Services",
  "services.comprehensive_solutions": "Comprehensive and Advanced Solutions",
  "services.spatial_data_collection": "Solutions for Spatial Data Collection and Satellite Image Analysis",
  "services.spatial_data_description": "Kuwait Maps offers spatial data collection services from various sources using remote sensing technologies and open-source GIS software.",
  "services.field_data_collection": "Field Data Collection",
  "services.custom_survey_models": "Building Custom Survey Models",
  "services.project_sharing": "Project Sharing with Field Teams",
  "services.satellite_analysis": "Analysis of Satellite and Drone-Captured Images",
  "services.features": "Features:",
  "services.benefits": "Benefits:",
  "services.high_accuracy": "High Data Accuracy",
  "services.time_effort_saving": "Saving Time and Effort",
  "services.comprehensive_reports": "Comprehensive and Detailed Reports",
  
  "services.electronic_mobile_maps": "Electronic and Mobile Maps",
  "services.electronic_maps_description": "Interactive electronic maps for websites and mobile apps for adding and editing spatial data",
  "services.interactive_web_maps": "Interactive Web Maps",
  "services.mobile_applications": "Mobile Applications",
  "services.spatial_data_editing": "Add and Edit Spatial Data",
  "services.geographic_phenomena": "Display Geographic Phenomena",
  "services.user_friendly": "User-Friendly Interface",
  "services.device_compatibility": "Compatible with All Devices",
  "services.instant_updates": "Instant Updates",
  
  "services.business_location_publishing": "Business Location Publishing and Optimization",
  "services.business_location_description": "Add, edit, and enhance business location data and publish it on various social media platforms",
  "services.features services.search_optimization": "Search Engine Optimization",
  "services.social_media_publishing": "Social Media Publishing",
  "services.location_data_updates": "Location Data Updates",
  
  "services.digital_marketing": "Digital Marketing Strategies",
  "services.customer_reach": "Increase Customer Reach",
  "services.digital_visibility": "Enhance Digital Visibility",
  "services.sales_growth": "Sales Growth",
  
  "services.specialized_service": "Specialized Service",
  "services.google_business_account": "Google Maps Business Account Service",
  "services.google_business_description": "Comprehensive services for managing and optimizing your business account on Google Maps to increase reach and sales",
  "services.account_verification": "Google Maps Business Account Verification",
  "services.account_verification_desc": "Verifying account ownership and maintaining the account",
  "services.data_management": "Data Management and Processing",
  "services.data_management_desc": "Managing account data, processing photos, and editing data and errors",
  "services.business_documentation": "Business Activity Documentation and Publishing",
  "services.business_documentation_desc": "Websites, company directories, and Google Maps search engine",
  "services.performance_reports": "Performance and Competitive Reports",
  "services.performance_reports_desc": "Keyword competitiveness, review management, and performance reporting",
  "services.advertising_campaigns": "Advertising Campaigns",
  "services.advertising_campaigns_desc": "Various types of Google Maps and Google Search ads",
  
  "services.distinguished_service": "Premium Service",
  "services.dot_service": "The Dot Service",
  "services.dot_advanced_solutions": "Advanced Mapping Solutions",
  "services.dot_description": "Kuwait Maps aims to help business owners in various industries add their entities and related information to online mapping platforms, focusing primarily on Google Maps.",
  "services.dot_comprehensive": "By providing comprehensive 2D mapping solutions that include buildings, parking lots, stores, and landscapes, the company facilitates enhanced visibility and accessibility for businesses.",
  "services.dot_features": "Features of the DOT Project Service",
  
  "services.start_project": "Start Your Project Today",
  "services.free_consultation": "Need a Free Consultation?",
  "services.consultation_description": "Contact us today and discover how our specialized services can help grow your business and achieve your goals.",
  "services.get_consultation": "Get a Free Consultation",
  "services.view_work": "View Our Work",
  "services.search_optimization": "Search Engine Optimization",
  
  "reports.badge": "Advanced Analytics and Reports",
  "reports.title": "Reports and Analytics",
  "reports.description": "Comprehensive reports and advanced analytics that help you make informed decisions and improve your business performance",
  "reports.completed_reports": "Completed Report",
  "reports.satisfied_clients": "Satisfied Client",
  "reports.data_accuracy": "Data Accuracy",
  "reports.continuous_updates": "Continuous Updates",
  "reports.report_types_badge": "Types of Reports",
  "reports.report_types_title": "Comprehensive and Specialized Reports",
  "reports.business_performance": "Business Performance Reports",
  "reports.business_performance_desc": "Comprehensive analysis of business account performance on Google Maps with key performance indicators",
  "reports.report_includes": "The Report Includes:",
  "reports.business_performance_feature1": "Visit and View Analysis",
  "reports.business_performance_feature2": "Content Engagement Rate",
  "reports.business_performance_feature3": "Review and Rating Analysis",
  "reports.business_performance_feature4": "Performance Comparison with Competitors",
  "reports.deliverables": "Deliverables:",
  "reports.business_performance_deliverable1": "Detailed Monthly Report",

  
  "reports.badge": "Advanced Analytics & Reports",
  "reports.title": "Reports & Analytics",
  "reports.description": "Comprehensive reports and advanced analytics to help you make informed decisions and improve your business performance",
  "reports.completed_reports": "Completed Reports",
  "reports.satisfied_clients": "Satisfied Clients",
  "reports.data_accuracy": "Data Accuracy",
  "reports.continuous_updates": "Continuous Updates",
  "reports.report_types_badge": "Report Types",
  "reports.report_types_title": "Comprehensive & Specialized Reports",
  "reports.business_performance": "Business Performance Reports",
  "reports.business_performance_desc": "Comprehensive analysis of business account performance on Google Maps with key performance indicators",
  "reports.report_includes": "Report includes:",
  "reports.business_performance_feature1": "Visit and view analysis",
  "reports.business_performance_feature2": "Content engagement rate",
  "reports.business_performance_feature3": "Review and rating analysis",
  "reports.business_performance_feature4": "Performance comparison with competitors",
  "reports.deliverables": "Deliverables:",
  "reports.business_performance_deliverable1": "Detailed monthly report",
  "reports.business_performance_deliverable2": "Interactive charts",
  "reports.business_performance_deliverable3": "Improvement recommendations",
  "reports.competitive_analysis": "Competitive Analysis Reports",
  "reports.competitive_analysis_desc": "Comprehensive comparative study of your market position with strength and weakness analysis",
  "reports.competitive_analysis_feature1": "Direct competitors analysis",
  "reports.competitive_analysis_feature2": "Keyword comparison",
  "reports.competitive_analysis_feature3": "Marketing strategies analysis",
  "reports.competitive_analysis_feature4": "Growth and development opportunities",
  "reports.competitive_analysis_deliverable1": "Quarterly competitive report",
  "reports.competitive_analysis_deliverable2": "Strategic action plan",
  "reports.competitive_analysis_deliverable3": "Competitor matrix",
  "reports.performance_monitoring": "Performance Monitoring Reports",
  "reports.performance_monitoring_desc": "Ongoing monitoring of project and system performance with instant alerts and trend analysis",
  "reports.performance_monitoring_feature1": "Real-time performance tracking",
  "reports.performance_monitoring_feature2": "Error and issue alerts",
  "reports.performance_monitoring_feature3": "Usage trend analysis",
  "reports.performance_monitoring_feature4": "Preventive maintenance reports",
  "reports.performance_monitoring_deliverable1": "Interactive dashboard",
  "reports.performance_monitoring_deliverable2": "Weekly reports",
  "reports.performance_monitoring_deliverable3": "Instant alerts",
  "reports.spatial_data": "Spatial Data Reports",
  "reports.spatial_data_desc": "In-depth analysis of geographic and spatial data with accurate statistics and valuable insights",
  "reports.spatial_data_feature1": "Geographic distribution analysis",
  "reports.spatial_data_feature2": "Population density maps",
  "reports.spatial_data_feature3": "Movement pattern analysis",
  "reports.spatial_data_feature4": "Geographic area statistics",
  "reports.spatial_data_deliverable1": "Analytical maps",
  "reports.spatial_data_deliverable2": "Spatial databases",
  "reports.spatial_data_deliverable3": "Statistical reports",
  "reports.sample_reports_badge": "Sample Work",
  "reports.sample_reports_title": "Completed Reports",
  "reports.sample_reports_desc": "Examples of reports and analyses we have completed for our clients",
  "reports.sample_report1_title": "360 Mall Performance Report",
  "reports.sample_report1_type": "Performance Report",
  "reports.sample_report1_pages": "25 pages",
  "reports.sample_report1_desc": "Comprehensive analysis of the 360 Mall business account performance on Google Maps",
  "reports.sample_report1_date": "December 2024",
  "reports.key_results": "Key Results:",
  "reports.sample_report1_highlight1": "45% increase in visits",
  "reports.sample_report1_highlight2": "Improved rating to 4.8/5",
  "reports.sample_report1_highlight3": "60% growth in reviews",
  "reports.sample_report2_title": "Competitive Study of Shopping Malls",
  "reports.sample_report2_type": "Competitive Analysis",
  "reports.sample_report2_pages": "40 pages",
  "reports.sample_report2_desc": "Comparative analysis of major shopping malls in Kuwait",
  "reports.sample_report2_date": "November 2024",
  "reports.sample_report2_highlight1": "Analysis of 15 major malls",
  "reports.sample_report2_highlight2": "Strategy comparisons",
  "reports.sample_report2_highlight3": "Identified growth opportunities",
  "reports.sample_report3_title": "Kuwait Spatial Data Report",
  "reports.sample_report3_type": "Spatial Data",
  "reports.sample_report3_pages": "60 pages",
  "reports.sample_report3_desc": "Comprehensive analysis of spatial and geographic data in Kuwait",
  "reports.sample_report3_date": "October 2024",
  "reports.sample_report3_highlight1": "Interactive maps",
  "reports.sample_report3_highlight2": "Demographic statistics",
  "reports.sample_report3_highlight3": "Population distribution analysis",
  "reports.view_report": "View Report",
  "reports.report_features_badge": "Our Report Features",
  "reports.report_features_title": "Why Choose Our Reports?",
  "reports.feature4_title": "Future Forecasts",
  "reports.feature4_desc": "Predictions based on historical data analysis",
  "reports.feature3_title": "Comprehensive & Integrated Analysis",
  "reports.feature3_desc": "A holistic view covering all performance and development aspects",
  "reports.feature2_title": "Accurate & Reliable Data",
  "reports.feature2_desc": "Up-to-date and precise information from trusted and diverse sources",
  "reports.feature1_title": "Actionable Insights",
  "reports.feature1_desc": "Practical insights you can apply immediately to improve performance",
  "reports.cta_badge": "Get Your Custom Report",
  "reports.cta_title": "Need a Custom Report?",
  "reports.cta_desc": "Contact us today and get a detailed and comprehensive report for your business or project",
  "reports.cta_button2": "Explore Our Services",
  "reports.cta_button1": "Request Your Report Now"


  },
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("ar")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "ar" || savedLanguage === "en")) {
      setLanguage(savedLanguage)
    }
  }, [])

  useEffect(() => {
    localStorage.setItem("language", language)
    document.documentElement.lang = language
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr"
  }, [language])

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  const dir = language === "ar" ? "rtl" : "ltr"

  return <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>{children}</LanguageContext.Provider>
}
